site_name: HPC Container Maker
docs_dir: docs
hooks:
  - mkdocs_hooks.py
plugins:
  - search
  - mkapi:
      exclude:
        - hpccm.building_blocks.base
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorial: tutorial.md
  - Recipes: recipes.md
  - Workflows: workflows.md
  - Citation: citation.md
  - Documentation:
      - Building Blocks: $api/hpccm.building_blocks
      - Primitives: $api/hpccm.primitives
      - Miscellaneous:
          - $api/hpccm.config
          - $api/hpccm.recipe
          - $api/hpccm.Stage
theme:
  name: readthedocs
extra_css:
  - stylesheets/extra.css
validation:
  links:
    anchors: ignore
