name: Docker Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        recipe:
        - recipes/easybuild.py
        - recipes/examples/basic.py
        - recipes/examples/cloverleaf.py
        - recipes/examples/multistage.py
        - recipes/gromacs/gromacs.py
        - recipes/hpcbase-gnu-mvapich2.py
        - recipes/hpcbase-gnu-mvapich2.py --userarg centos=true
        - recipes/hpcbase-gnu-openmpi.py
        - recipes/hpcbase-gnu-openmpi.py --userarg centos=true
        - recipes/hpcbase-nvhpc-mvapich2.py --userarg nvhpc_eula_accept=yes
        - recipes/hpcbase-nvhpc-mvapich2.py --userarg nvhpc_eula_accept=yes centos=true
        - recipes/hpcbase-nvhpc-openmpi.py --userarg nvhpc_eula_accept=yes
        - recipes/hpcbase-nvhpc-openmpi.py --userarg nvhpc_eula_accept=yes centos=true
        - recipes/hpccm/bootstrap.py
        - recipes/lammps/lammps.py
        - recipes/milc/milc.py
        - recipes/mpi_bandwidth.py
        - recipes/osu_benchmarks/osu_benchmarks.py
        - recipes/spack.py

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six

    - name: Build container
      run: |
        ./hpccm.sh --recipe ${{ matrix.recipe }} > Dockerfile
        sudo docker build -t container -f Dockerfile .
