name: Docker Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        userargs: [none=none]
        context: [.]
        include:
          - recipe: recipes/easybuild.py
          - recipe: recipes/examples/basic.py
          - recipe: recipes/examples/cloverleaf.py
          - recipe: recipes/examples/multistage.py
          - recipe: recipes/gromacs/gromacs.py
          - recipe: recipes/hpcbase-gnu-mvapich2.py
          - recipe: recipes/hpcbase-gnu-mvapich2.py
            userargs: centos=true
          - recipe: recipes/hpcbase-gnu-openmpi.py
          - recipe: recipes/hpcbase-gnu-openmpi.py
            userargs: centos=true
          - recipe: recipes/hpcbase-nvhpc-mvapich2.py
            userargs: nvhpc_eula_accept=yes
          - recipe: recipes/hpcbase-nvhpc-mvapich2.py
            userargs: nvhpc_eula_accept=yes centos=true
          - recipe: recipes/hpcbase-nvhpc-openmpi.py
            userargs: nvhpc_eula_accept=yes
          - recipe: recipes/hpcbase-nvhpc-openmpi.py
            userargs: nvhpc_eula_accept=yes centos=true
          - recipe: recipes/hpccm/bootstrap.py
          - recipe: recipes/lammps/lammps.py
          - recipe: recipes/milc/milc.py
          - recipe: - recipes/mpi_bandwidth.py
          - recipe: recipes/osu_benchmarks/osu_benchmarks.py
            context: recipes/osu_benchmarks
          - recipe: recipes/spack.py

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six

    - name: Build container
      run: |
        ./hpccm.sh --recipe ${{ matrix.recipe }} --userarg ${{ matrix.userargs }} > Dockerfile
        sudo docker build -f Dockerfile ${{ matrix.context }}
